name: flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  flex_color_picker: ^3.6.0
  get_it: ^8.0.3
  shared_preferences: ^2.3.4
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true